namespace XmlBooster
{
    public enum EXmlBValidationErrorCause
    {
        VALIDATION_STRING_LENGTH_VIOLATION,
        VALIDATION_REG_EXPR_VIOLATION,
        VALIDATION_ATTRIBUTE_REQUIRED,
        VALIDATION_ELEMENT_REQUIRED,
        VALIDATION_RANGE_VIOLATION,
        VALIDATION_REFERENCE_TYPE_VIOLATION,
        VALIDATION_DISJUNCTION_VIOLATION,
        VALIDATION_PERM_VIOLATION,
    }
}