//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Value", Namespace="http://schemas.datacontract.org/2004/07/EFSIPCInterface.Values")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EFSService.DoubleValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EFSService.IntValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EFSService.StructureValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EFSService.StringValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EFSService.ListValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EFSService.BoolValue))]
    public partial class Value : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoubleValue", Namespace="http://schemas.datacontract.org/2004/07/EFSIPCInterface.Values")]
    [System.SerializableAttribute()]
    public partial class DoubleValue : EFSService.Value {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntValue", Namespace="http://schemas.datacontract.org/2004/07/EFSIPCInterface.Values")]
    [System.SerializableAttribute()]
    public partial class IntValue : EFSService.Value {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructureValue", Namespace="http://schemas.datacontract.org/2004/07/EFSIPCInterface.Values")]
    [System.SerializableAttribute()]
    public partial class StructureValue : EFSService.Value {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, EFSService.Value> ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, EFSService.Value> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringValue", Namespace="http://schemas.datacontract.org/2004/07/EFSIPCInterface.Values")]
    [System.SerializableAttribute()]
    public partial class StringValue : EFSService.Value {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListValue", Namespace="http://schemas.datacontract.org/2004/07/EFSIPCInterface.Values")]
    [System.SerializableAttribute()]
    public partial class ListValue : EFSService.Value {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EFSService.Value[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EFSService.Value[] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoolValue", Namespace="http://schemas.datacontract.org/2004/07/EFSIPCInterface.Values")]
    [System.SerializableAttribute()]
    public partial class BoolValue : EFSService.Value {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Priority", Namespace="http://schemas.datacontract.org/2004/07/EFSIPCInterface")]
    public enum Priority : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verification = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateInternal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Process = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateOutput = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CleanUp = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EFSService.IEFSService")]
    public interface IEFSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEFSService/GetVariableValue", ReplyAction="http://tempuri.org/IEFSService/GetVariableValueResponse")]
        EFSService.Value GetVariableValue(string variableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEFSService/SetVariableValue", ReplyAction="http://tempuri.org/IEFSService/SetVariableValueResponse")]
        void SetVariableValue(string variableName, EFSService.Value value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEFSService/Cycle", ReplyAction="http://tempuri.org/IEFSService/CycleResponse")]
        void Cycle(EFSService.Priority priority);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEFSServiceChannel : EFSService.IEFSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EFSServiceClient : System.ServiceModel.ClientBase<EFSService.IEFSService>, EFSService.IEFSService {
        
        public EFSServiceClient() {
        }
        
        public EFSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EFSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EFSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EFSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EFSService.Value GetVariableValue(string variableName) {
            return base.Channel.GetVariableValue(variableName);
        }
        
        public void SetVariableValue(string variableName, EFSService.Value value) {
            base.Channel.SetVariableValue(variableName, value);
        }
        
        public void Cycle(EFSService.Priority priority) {
            base.Channel.Cycle(priority);
        }
    }
}
